### ISSUE TITLE
Ability to create a route with multiple links

### ISSUE THREAD

**Issue by tommcclean** [tommcclean/cmpct.io#16]
The API at https://cmpct-api-tmp.azurewebsites.net/swagger/index.html now supports posting multiple links at once. The UI doesn't allow the user to submit more than one.

This issue is a feature request to post up to three links in a single route.

**Comment by highvoltag3** [comment]
@tommcclean This seems to be live already unless I'm missing something.

**Comment by tommcclean** [comment]
Ah yeah sorry, this one went in. If you are looking for anything to pick up, I have added a raft of new issues off the back of user feedback.
